/* eslint no-console: 0 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseFrontMatterContent } from "./parse.js";
import type { Scenario } from "./types.js";

const FIRST_COMMENT = /<!--([\s\S]*?)-->/;

const scenariosDir = path.resolve(import.meta.dirname, "../scenarios");
const outputPath = path.resolve(import.meta.dirname, "generated.ts");

const files = (await readdir(scenariosDir))
  .filter((file) => file.endsWith(".html"))
  .sort();

const scenarios: Scenario[] = [];

for (const file of files) {
  const html = await readFile(path.join(scenariosDir, file), "utf-8");
  const firstComment = FIRST_COMMENT.exec(html);
  const metadata = firstComment
    ? parseFrontMatterContent(firstComment[1])
    : null;

  scenarios.push({
    id: file.replace(/\.html$/, ""),
    title: metadata?.title ?? null,
    description: metadata?.description ?? null,
    tags: metadata?.tags ?? [],
    options: metadata?.options ?? {},
    html,
  });
}

const output = [
  "// Generated by `npm run generate`. Do not edit.",
  'import type { Scenario } from "./types.js";',
  "",
  `export const scenarios: Scenario[] = ${JSON.stringify(scenarios, null, 2)};`,
  "",
].join("\n");

await writeFile(outputPath, output, "utf-8");
console.log(`Generated ${String(scenarios.length)} scenarios.`);
