// Generated by `npm run generate`. Do not edit.
import type { Scenario } from "./types.js";

export const scenarios: Scenario[] = [
  {
    "id": "ancestor-class",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div class=\"aaa\">\n  <div class=\"bbb\">\n    <!-- expect: .aaa .bbb -->\n  </div>\n</div>\n\n<div class=\"ccc\">\n  <!-- this prevents creation of simple .bbb selector -->\n  <div class=\"bbb\"></div>\n</div>\n"
  },
  {
    "id": "class-combination",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div class=\"aaa bbb\"><!-- expect: .aaa.bbb --></div>\n<div class=\"aaa ccc\"></div>\n<div class=\"bbb ccc\"></div>\n"
  },
  {
    "id": "class-escaped-colon",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<!--\n  Class names containing characters that must be escaped in a selector.\n  The generated selector has to escape them AND still resolve back to the\n  element, which is what the old greedy comment splitter made impossible to\n  express: it split `expect: .aaa\\:bbb` on the LAST colon.\n-->\n\n<div class=\"aaa:bbb\"><!-- expect: .aaa\\:bbb --></div>\n\n<div class=\"ccc+ddd\"><!-- expect: .ccc\\+ddd --></div>\n"
  },
  {
    "id": "class-single",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div class=\"aaa bbb\"><!-- expect: .bbb --></div>\n<div class=\"aaa ccc\"></div>\n"
  },
  {
    "id": "deep-selector",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div id=\"aaa\" class=\"aaa\">\n  <div>\n    <div class=\"aaa\"><!-- expect:  #aaa .aaa --></div>\n  </div>\n</div>\n"
  },
  {
    "id": "multiple-classes",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div class=\"aaa bbb\">\n  <!-- expect: .aaa.bbb -->\n</div>\n\n<!-- These two elements prevent the generator from creating simple single-class selector (e.g. \".aaa\" or \".bbb\". -->\n<div class=\"aaa\"></div>\n<div class=\"bbb\"></div>\n\n"
  },
  {
    "id": "multiple-elements-different-tags",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div><!-- identifier: needle --></div>\n<p><!-- identifier: needle --></p>\n\n<!-- expect: needle; div, p -->\n"
  },
  {
    "id": "multiple-elements-fallback",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div><!-- identifier: needle --></div>\n<div><!-- identifier: needle --></div>\n\n<!-- this prevents creation of common `div` selector -->\n<div></div>\n\n<!--\n  NOTE: The first two parts of the fallback selector chain are:\n  :root -> HTML\n  :nth-child(2) -> BODY\n-->\n<!-- expect: needle; :root > :nth-child(2) > :nth-child(1), :root > :nth-child(2) > :nth-child(2) -->\n"
  },
  {
    "id": "multiple-elements-nested",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div class=\"aaa\">\n  <!-- identifier: needle -->\n  <div class=\"aaa\">\n    <!-- identifier: needle -->\n    <div class=\"aaa\">\n      <!-- identifier: needle -->\n    </div>\n  </div>\n</div>\n\n<!-- expect: needle; .aaa -->\n"
  },
  {
    "id": "multiple-elements-no-shared-class",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div class=\"aaa\"><!-- identifier: needle --></div>\n<p class=\"bbb\"><!-- identifier: needle --></p>\n\n<!-- expect: needle; .aaa, .bbb -->\n"
  },
  {
    "id": "multiple-elements-shared-class",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div class=\"aaa bbb\"><!-- identifier: needle --></div>\n<div class=\"bbb ccc\"><!-- identifier: needle --></div>\n\n<!-- expect: needle; .bbb -->\n"
  },
  {
    "id": "multiple-elements",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div class=\"aaa\"><!-- identifier: needle --></div>\n<div class=\"aaa\"><!-- identifier: needle --></div>\n<div class=\"aaa\"><!-- identifier: needle --></div>\n\n<!-- expect: needle; .aaa -->\n"
  },
  {
    "id": "options-combine-within-selector",
    "title": "Option combineWithinSelector disabled",
    "description": "With combining disabled, two class names must not be merged into one selector.",
    "tags": [
      "options",
      "class"
    ],
    "options": {
      "combineWithinSelector": false
    },
    "html": "<!-- scenario\ntitle: Option combineWithinSelector disabled\ndescription: With combining disabled, two class names must not be merged into one selector.\ntags: options, class\noptions: {\"combineWithinSelector\": false}\n-->\n\n<div class=\"aaa bbb\">\n  <!-- expect-not: .aaa.bbb -->\n  <!-- expect-not: .bbb.aaa -->\n</div>\n<div class=\"aaa\"></div>\n<div class=\"bbb\"></div>\n"
  },
  {
    "id": "options-include-tag",
    "title": "Option includeTag",
    "description": "With includeTag, every part of the selector is prefixed with its tag name.",
    "tags": [
      "options",
      "tag"
    ],
    "options": {
      "includeTag": true,
      "selectors": [
        "class"
      ]
    },
    "html": "<!-- scenario\ntitle: Option includeTag\ndescription: With includeTag, every part of the selector is prefixed with its tag name.\ntags: options, tag\noptions: {\"includeTag\": true, \"selectors\": [\"class\"]}\n-->\n\n<div class=\"aaa bbb\">\n  <div class=\"aaa\"><!-- expect: div.bbb div.aaa --></div>\n</div>\n"
  },
  {
    "id": "options-root",
    "title": "Option root",
    "description": "Only the marked root is searched, so the span outside it is not a conflict.",
    "tags": [
      "options",
      "root"
    ],
    "options": {},
    "html": "<!-- scenario\ntitle: Option root\ndescription: Only the marked root is searched, so the span outside it is not a conflict.\ntags: options, root\n-->\n\n<span></span>\n\n<div><!-- root -->\n  <span><!-- expect: span --></span>\n</div>\n"
  },
  {
    "id": "selector-class",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div class=\"aaa\">\n  <!-- expect: .aaa -->\n</div>\n"
  },
  {
    "id": "selector-descendant",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div>\n  <span>\n    <!-- expect: div > span -->\n    <span></span>\n  </span>\n</div>\n"
  },
  {
    "id": "selector-fallback",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div><!-- identifier: needle --></div>\n\n<!-- this prevents creation of a `div` selector -->\n<div></div>\n\n<!--\n  NOTE: The first two parts of the fallback selector chain are:\n  :root -> HTML\n  :nth-child(2) -> BODY\n-->\n<!-- expect: needle; :root > :nth-child(2) > :nth-child(1) -->\n"
  },
  {
    "id": "selector-type-combination",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div id=\"first\">\n  <div class=\"aaa\">\n    <!-- expect: #first .aaa -->\n  </div>\n</div>\n\n<div id=\"second\">\n  <div class=\"aaa\"></div>\n</div>\n"
  },
  {
    "id": "shadow-dom-basic",
    "title": "Shadow DOM",
    "description": "A selector for an element inside an open shadow root, scoped to that root.",
    "tags": [
      "shadow-dom",
      "root"
    ],
    "options": {},
    "html": "<!-- scenario\ntitle: Shadow DOM\ndescription: A selector for an element inside an open shadow root, scoped to that root.\ntags: shadow-dom, root\n-->\n\n<div class=\"shadowElement\"></div>\n\n<div>\n  <template shadowrootmode=\"open\">\n    <!-- root -->\n    <div class=\"shadowElement\"><!-- expect: .shadowElement --></div>\n  </template>\n</div>\n"
  },
  {
    "id": "shadow-dom-fallback",
    "title": "Shadow DOM fallback",
    "description": "Children of a shadow root with nothing to identify them fall back to a scoped positional selector.",
    "tags": [
      "shadow-dom",
      "root",
      "fallback"
    ],
    "options": {},
    "html": "<!-- scenario\ntitle: Shadow DOM fallback\ndescription: Children of a shadow root with nothing to identify them fall back to a scoped positional selector.\ntags: shadow-dom, root, fallback\n-->\n\n<div>\n  <template shadowrootmode=\"open\">\n    <!-- root -->\n    <div><!-- expect: :nth-child(1) --></div>\n    <div></div>\n  </template>\n</div>\n"
  },
  {
    "id": "tag",
    "title": null,
    "description": null,
    "tags": [],
    "options": {},
    "html": "<div><!-- expect: div --></div>\n<p>\n  <!-- expect: p -->\n  <span><!-- expect: span --></span>\n</p>\n"
  }
];
